name:                type-record
version:             0.1.0.0
github:              "dmytr/type-record"
license:             MIT
author:              "Dmytro Iaroslavskyi"
copyright:           "2018 Dmytro Iaroslavskyi"
description:         Please see the README on GitHub at <https://github.com/dmytr/type-record#readme>
synopsis:            Type-level operations and constraints on records

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- singletons

library:
  source-dirs: src

tests:
  type-record-test:
    main:                Spec.hs
    source-dirs:
    - test
    - examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-record

ghc-options: -Wall -fhide-source-paths -optP-Wno-nonportable-include-path
